### ISSUE TITLE
New Ship menu incorrectly assumes all projects have a default branch name of "main"

### ISSUE THREAD

**Issue by arnavravinder** [hackclub/high-seas#720] opened 2024-11-12 09:48 UTC
When you submit a new ship, if you've entered a GitHub URL it automatically collapses the README URL box. Currently, it just blindly sets the URL to [https://raw.githubusercontent.com/{username}/{repository}/refs/heads/main/README.md](https://raw.githubusercontent.com/%7Busername%7D/%7Brepository%7D/refs/heads/main/README.md), but it should try get the default branch name first in case the default branch is not main (ie people who still use master or people that have changed it to something else)

**Comment by maxwofford** [comment] 2024-11-12 17:54
Closing as duplicate of https://github.com/hackclub/high-seas/issues/714

**Closed by maxwofford** 2024-11-12 17:54 UTC
Labels: bug, shipyard
